name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build image
      run: "export SHELL=/bin/bash\neval $(minikube -p minikube docker-env)\ndocker build -f ./Dockerfile -t siarheisaroka/node-app:latest .\ndocker push siarheisaroka/node-app:latest\necho -n \"verifying images:\"\ndocker images         \n"
    - name: Deploy to minikube
      run: kubectl apply -f k8s-node-app.yaml
    - name: Test service URLs
      run: |
        minikube service list
        minikube service nodejs-app --url
        apt update
        apt install curl -y
        addr=$(minikube service nodejs-app --url)
        curl $addr

